# window_opacity = 1.0

[colors]
# background = "#282828"
# foreground = "#eaeaea"

[font]
size = 12.0

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
# x = 10
# y = 10

