#!/bin/bash

DIRNAME="${0%/*}"
source $DIRNAME/../bash/lib/common
source $DIRNAME/common-git
NOTIFY_EMAIL="$DIRNAME/../bin/notify-email"

cd $LOCAL_PATH

OLD_IFS="$IFS"
IFS=""

CHANGES="`$(which git) log -p --no-merges --since \"yesterday\"`"

if [ -z "$CHANGES" ];
then
    echo "No changes detected"
else
    echo "Changes detected! Emailing!"

    DIR=`pwd`
    DIRNAME=`dirname $DIR`
    DOMAIN=`basename $DIRNAME`

    "$NOTIFY_EMAIL" "GIT CHANGES TO $DOMAIN" "$CHANGES"

fi

IFS="$OLD_IFS"
