#!/bin/bash

DIRNAME="${0%/*}"
source $DIRNAME/../bash/lib/echos

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

if [ -z "${1// }" ]
then
    echo "Usage: full-backup <path-to-root-folder>"
    exit
fi

pushd .

if [ -d "$1" ]
then
    ROOT_PATH=`realpath $1`
    cd $ROOT_PATH
    echo_info "Root: `pwd`"
else
    echo_error "Directory \"$1\" does not exist. Aborting"
    popd
    exit
fi

echo_info "Database Backup"
mysqlbk

echo_info "GIT Pull"
pull

echo_info "Sync Folders"
sync-folders

popd


