#!/bin/bash

DIRNAME="${0%/*}"
source $DIRNAME/../bash/lib/common

cd $LOCAL_BASE
if [ -z ${LOCAL_BASE+x} ]
then
    echo "Error: No LOCAL_BASE value set"
    exit
fi
,
if [ -z ${LOCAL_PATH+x} ]
then
    echo "Error: No LOCAL_PATH value set"
    exit
fi

if [ -z $SSH_KEY ]
then
    SSH_KEY_OVERRIDE=""
else
    SSH_KEY_OVERRIDE="-i $SSH_KEY"
fi

echo -e "${GREEN}" "SSH Host: $SSH_HOST" "${NC}"
echo -e "${GREEN}" "SSH Port: $SSH_PORT" "${NC}"
echo -e "${GREEN}" "SSH Key:  $SSH_KEY" "${NC}"
echo -e "${GREEN}" "SSH User: $SSH_USER" "${NC}"
echo -e "${GREEN}" "SSH Path: $SSH_PATH" "${NC}"
echo -e "${GREEN}" "Local Base: $LOCAL_BASE" "${NC}"
echo -e "${GREEN}" "Local Path: $LOCAL_PATH" "${NC}"

check_gitignore
check_git_repo
git_commit 
git_pull

echo -e "${GREEN}" "Done" "${NC}"
echo ""
